package com.cognizant.ipm.adapter.wizard;

import java.util.ListResourceBundle;

public class CloudResourceBundle extends ListResourceBundle
{
  public Object[][] getContents()
  {
    return contents;
  }
  
  static final Object[][] contents = {
	{ "CL_OP_NO_BO_MESSAGE_LBL", "There are no business objects needed for the selected operation" }, 
	{ "CL_QT_QUERY_TEST_DIALOG_TITLE", "Query Test" }, 
	{ "CL_QT_QUERY_TEST_BTN", "Test" }, 
	{ "CL_QT_QUERY_TEST_TIP", "Run Query Test tool" }, 
	{ "CL_QT_INTRO_TXT", "Enter a value for each bind parameter and then execute query. After testing, if you've modified the Query Statement, you may hit Save to retain the new statement.  Otherwise, hit Done." }, 
	{ "CL_QT_STATEMENT_LBL", "Query &Statement:" }, 
	{ "CL_QT_STATEMENT_TIP", "Query Statement to be executed" }, 
	{ "CL_QT_REFRESH_TIP", "Refresh Bind Parameters if Query Statement changed." }, 
	{ "CL_QT_EXECUTE_TIP", "Execute Query" }, 
	{ "CL_QT_EXECUTE_BTN", "Execute Query" }, 
	{ "CL_QT_RESULT_LBL", "Results from {0}:" }, 
	{ "CL_QT_RESULT_TIP", "Output from query execution" }, 
	{ "CL_QT_PARAM_VALUE_TIP", "Parameter value for :{0}" }, 
	{ "CL_QT_BIND_PARAMETERS", "Bind Parameters:" }, 
	{ "CL_QT_INVALID_BIND_PARAMETER_ERROR", "Invalid characters used in bind parameter name: {0}" }, 
	{ "CL_QT_INVALID_BIND_PARAMETER_TITLE", "Bind Variable Error" }, 
	{ "CL_QT_PARAMETER_VALUE_LBL", "{0} Value:" }, 
	{ "CL_QT_QUERY_TEST_SAVE_BUTTON", "&Save" }, 
	{ "CL_QT_QUERY_TEST_DONE_BUTTON", "&Done" }, 
	{ "CL_QT_BIND_VARIABLE_ERROR_TITLE", "Bind Variable Error" }, 
	{ "CL_QT_UNBOUND_VARIABLE_ERROR", "The Query Statement contains the bind variable {0} which has not been bound. Hit the Refresh button to see all bind parameters needed." }, 
	{ "CL_QT_BIND_VARIABLE_DUPLICATE_ERROR", "The Query Statement has more than one occurance of the bind variable {0}." }, 
	{ "CL_QT_EXECUTE_QUERY_EXCEPTION", "The query execution raised the following exception: \n{0}" }, 
	{ "CL_QT_EXECUTE_QUERY_EXCEPTION_TITLE", "Query Execution Failed" }, 
	{ "CL_QT_EXECUTE_QUERY_STATUS_WAIT", "Please wait..." }, 
	{ "CL_QT_EXECUTE_QUERY_STATUS_DETAIL", "Executing Statement ..." }, 
	{ "CL_QT_RETURN_COUNT_LBL", "Result Object Count:" }, 
	{ "CL_QT_BOUND_QUERY_STATEMENT", "\n\nThe query statement executed: \n{0}" }, 
	{ "CL_WIZARD_TRANSFORMATIONMODEL_REBUILD_ERROR", "TransformationModelBuilder.rebuild() failed to create TransformationModel." }, 
	{ "CL_WIZARD_READ_DATA_MODEL_ERROR_TITLE", "Read Data Model Error" }, 
	{ "CL_CONNECTION_MAIN_TAB_TEXT", "Design Time" }, 
	{ "CL_CONNECTION_MAIN_TAB_TIP", "Properties for design time connection" }, 
	{ "CL_CONNECTION_SECOND_TAB_TEXT", "Run Time" }, 
	{ "CL_CONNECTION_SECOND_TAB_TIP", "Properties for run time connection" }, 
	{ "CL_CONNECTION_WSDL_LOCATION_LBL", "&WSDL Location:" }, 
	{ "CL_CONNECTION_USER_NAME_LBL", "&User ID:" }, 
	{ "CL_CONNECTION_USER_NAME_TIP", "Enter user id for connection" }, 
	{ "CL_CONNECTION_PASSWORD_LBL", "&Password:" }, 
	{ "CL_CONNECTION_PASSWORD_TIP", "Enter password for connection" }, 
	{ "CL_CONNECTION_CSFKEY_LBL", "&Authentication Key:" }, 
	{ "CL_CONNECTION_CSFKEY_TIP", "Select the key that will be used to extract authentication info from the CSF key store" }, 
	{ "CL_CONNECTION_REFRESH_CB", "&Clear Cache" }, 
	{ "CL_CONNECTION_REFRESH_TIP", "Clear cache so that all metadata is refreshed from Cloud Server" }, 
	{ "CL_CONNECTION_TEST_BTN", "&Test Connection" }, 
	{ "CL_CONNECTION_TEST_TIP", "Test that Connection is working" }, 
	{ "CL_CONNECTION_LOAD_METADATA_ERROR", "Load of zuora Metadata failed. Exception = {0} ." }, 
	{ "CM_CN_CONNECTION_TEST_SUCCESS", "Success!" }, 
	{ "CM_CN_CONNECTION_INTRO", "A zuora Cloud Server connection is required to access the operations and business objects available." }, 
	{ "CL_CONNECTION_OFFLINE_CB", "&Offline Configuration" }, 
	{ "CL_CONNECTION_OFFLINE_TIP", "Run this wizard offline with no network connections required. Going offline will download all metadata needed" }, 
	{ "CL_CONNECTION_TEST_OFFLINE_ERROR", "Test Connection is not available in offline mode." }, 
	{ "CL_QUERY_TEST_OFFLINE_ERROR", "Query Test is not available in offline mode." }, 
	{ "CL_CONNECTION_OFFLINE_TITLE", "Connection is Offline" }, 
	{ "CL_CONNECTION_OFFLINE_WARNING", "To run offline requires downloading all Cloud server metadata that may be needed. This may take a few minutes. Continue?" }, 
	{ "CL_CONNECTION_OFFLINE_WARNING_TITLE", "Metadata Download Required" }, 
	{ "CL_CONNECTION_DOWNLOAD_STATUS_WAIT", "Please wait..." }, 
	{ "CL_CONNECTION_DOWNLOAD_STATUS_DETAIL", "Downloading required metadata ..." }, 
	{ "CL_CREDENTIAL_ADD_TITLE", "Add Credential" }, 
	{ "CL_CONNECTION_CREDENTIAL_ADD_TIP", "Add a new authentication credential to CSF key store" }, 
	{ "CL_CONNECTION_CREDENTIAL_DELETE_TIP", "Delete the selected authentication credential from CSF key store" }, 
	{ "CL_CONNECTION_CREDENTIAL_DELETE_CONFIRM", "Are you sure you want to delete the credentials for key {0} ?" }, 
	{ "CL_CONNECTION_CREDENTIAL_DELETE_CONFIRM_TITLE", "Confirm Credential Delete" }, 
	{ "CL_CREDENTIAL_INTRO", "Create a new password credential by supplying a user name, password and the key alias.  The new credential will be added to the oracle.wsm.security credential map." }, 
	{ "CL_CREDENTIAL_USER_NAME_LBL", "&User ID:" }, 
	{ "CL_CREDENTIAL_USER_NAME_TIP", "Enter user id for credential" }, 
	{ "CL_CREDENTIAL_PASSWORD_LBL", "&Password:" }, 
	{ "CL_CREDENTIAL_PASSWORD_TIP", "Enter password for credential" }, 
	{ "CL_CREDENTIAL_CSFKEY_LBL", "&CSF Key:" }, 
	{ "CL_CREDENTIAL_CSFKEY_TIP", "Enter key for credential" }, 
	{ "CL_DH_METADATA_ERROR", "Exception occurred while loading header metadata.  Exception={0}" }, 
	{ "CL_DH_METADATA_ERROR_TITLE", "Metadata Load Error" }, 
	{ "CL_DH_TAB_TEXT", "Header Properties" }, 
	{ "CL_DH_TAB_TIP", "Header properties for operation" }, 
	{ "CL_DH_CHECKBOX_TIP", "Check box to enable property" }, 
	{ "CL_DH_PROPERTY_VALUE_TIP", "Value for property {0}" }, 
	{ "CM_CN_CONNECTION_FIELDS_MISSING", "The fields are missing : " }, 
	{ "CM_CN_CONNECTION_USER_ID", "User ID" }, 
	{ "CM_CN_CONNECTION_PASSOWORD", " Password" }, 
	{ "CM_CN_CONNECTION_WSDL_LOCATION", "WSDL Location" }, 
	{ "CM_CN_CONNECTION_AUTHENTICATION_KEY", "Authentication Key" }, 
	{ "CM_CN_INVALID_USERNAME_MESSAGE", "The username should be in the form of valid email id." }, 
	{ "CM_CN_METADATA_LOAD_ERROR_TITLE", "Metadata Load Error" }, 
	{ "CL_OP_CONFIGURE_OPERATION_BTN", "&Configure cloud operation" }, 
	{ "CL_OP_CONFIGURE_OPERATION_TIP", "Configure single operation" }, 
	{ "CL_OP_CONFIGURE_BATCH_BTN", "Configure &multiple operations in a Batch" }, 
	{ "CL_OP_CONFIGURE_BATCH_TIP", "Configure multiple operations in a Batch" }, 
	{ "CL_OP_MOVE_UP_BTN", "Move object up in sequence" }, 
	{ "CL_OP_MOVE_DOWN_BTN", "Move object down in sequence" }, 
	{ "CL_OP_ADD_OPERATION_BTN", "add operation" }, 
	{ "CL_OP_REMOVE_OPERATION_BTN", "delete operation" }, 
	{ "CL_OP_UPDATE_OPERATION_BTN", "edit operation" }, 
	{ "CL_OP_OPERATION_TABLE_HEADER", "Operations" }, 
	{ "CL_OP_ADD_OPERATION_TITLE", "Add Operation" }, 
	{ "CL_OP_ADD_OPERATION_INTRO", "Select a zuora Cloud Operation and its primary business objects and specify a unique WSDL Operation name." }, 
	{ "CL_OP_API_LBL", "Operation Category:" }, 
	{ "CL_OP_API_TIP", "Select operation category api" }, 
	{ "CL_OP_VERSION_LBL", "API &Version:" }, 
	{ "CL_OP_VERSION_TIP", "Version of the selected api" }, 
	{ "CL_OP_OPERATION_LBL", "SFDC Operation:" }, 
	{ "CL_OP_OPERATION_TIP", "select cloud operation for this adapter instance" }, 
	{ "CL_OP_WSDL_OPERATION_LBL", "WSDL &Operation:" }, 
	{ "CL_OP_WSDL_MESSAGE_LBL", "WSDL &Message:" }, 
	{ "CL_OP_WSDL_TIP", "Unique name to be exposed in generated WSDL for this operation" }, 
	{ "CL_OP_BUSINESS_OBJECT_HEADER", "Business Objects" }, 
	{ "CL_OP_BUSINESS_OBJECT_RECENT_FILTER", "recent" }, 
	{ "CL_OP_BUSINESS_OBJECT_SEARCH_FILTER", "filter" }, 
	{ "CL_OP_BUSINESS_OBJECT_SEARCH_FILTER_TIP", "Business Object will be filtered by search text." }, 
	{ "CL_OP_QUERY_STATEMENT", "Query Statement" }, 
	{ "CL_OP_QUERY_BUILDER_TIP", "Invoke SOSL_SOQL Editor Tool" }, 
	{ "CL_OP_BUSINESS_OBJECT_MOVE_DOWN", "Move object down in sequence" }, 
	{ "CL_OP_BUSINESS_OBJECT_MOVE_UP", "Move object up in sequence" }, 
	{ "CL_OP_WSDL_MESSAGE_NAME_EXISTS_ERROR", "WSDL Message name {0} is already used in this adapter instance.  Specify a unique WSDL Operation name" }, 
	{ "CL_OP_WSDL_MESSAGE_NAME_EXISTS_ERROR_TITLE", "WSDL Message Uniqueness Error" }, 
	{ "CL_WSDL_OPERATION_COLUMN", "WSDL Operation" }, 
	{ "CL_CLOUD_OPERATION_COLUMN", "Cloud Operation" }, 
	{ "CL_BUSINESS_OBJECTS_COLUMN", "Business Objects" }, 
	{ "WSDL_NOT_FOUND", "Provided WSDL not Found" }, 
	{ "OP_QUERY_STATEMENT", "Query Statement" }, 
	{ "OP_QUERYALL_STATEMENT", "QueryAll Statement" }, 
	{ "OP_SEARCH_STATEMENT", "Search Statement" }, 
	{ "EMPTY_HEADER_PROPERTY_ERROR", "Please provide the header value for the selected header property!!!" }, 
	{ "INVALID_HEADER_PROPERTY__VALUE_ERROR", "Please provide numeric value for " }, 
	{ "HEADER_MIN_MAJ_INCLUSIVE_ERROR", "Package version header fields minorNumber and majorNumber are mutually inclusive. Either select both or none. Namespace is optional, but should be used with minorNumber and majorNumber." }, 
	{ "ADAPTER_HEADER", "zuora Cloud Adapter Configuration Wizard" }, 
	{ "WELCOME_MESSAGE_CREATE", "This wizard helps you create a service using a zuora Cloud Adapter. You will be asked to specify configuration parameters and define an operation for the service." }, 
	{ "WELCOME_MESSAGE_UPDATE", "This wizard helps you update a zuora Cloud Adapter service. You will be asked to specify configuration parameters and define an operation for the service." }, 
	{ "SERVICE_TYPE_HEADER", "zuora Cloud Adapter" }, 
	{ "CONNECTION_PAGE_HEADER", "zuora Cloud Server Connection" }, 
	{ "CONNECTION_API_TIP", "Select zuora API" }, 
	{ "CONNECTION_API_LBL", "&zuora API: " }, 
	{ "CONNECTION_ENDP_LBL", "&Endpoint URL: " }, 
	{ "CONNECTION_ENDP_FLD_TIP", "Built Endpoint URL" }, 
	{ "CONNECTION_ENDP_BTN_TIP", "Endpoint URL Builder" }, 
	{ "CONNECTION_ENDP_RESET_BTN_TIP", "Reset Endpoint URL" }, 
	{ "CONNECTION_ENDP_BUILDER_HOSTNAME_LBL", "Hostname: " }, 
	{ "CONNECTION_ENDP_VALIDATION_NOT_STARTS_WITH_PROTOCOL_ERROR", "Custom endpoint URL does not start with \"https://\"" }, 
	{ "CONNECTION_ENDP_VALIDATION_ENDS_WITH_PROTOCOL_ERROR", "Custom endpoint URL can not ends with \"https://\"" }, 
	{ "CONNECTION_ENDP_VALIDATION_ENDS_WITH_SUBPART_ERROR", "Custom endpoint URL can not ends with \"/services/Soap/c/\"" }, 
	{ "CONNECTION_ENDP_VALIDATION_SUBPART_MISSING", "Custom endpoint URL does not contain \"/services/Soap/c/\"" }, 
	{ "CONNECTION_ENDP_DEFAULT", "https://login.zuora.com/services/Soap/c/29.0" }, 
	{ "CONNECTION_ENDP_DEFAULT_PROTOCOL", "https://" }, 
	{ "CONNECTION_ENDP_DEFAULT_SUBPART", "/services/Soap/c/" }, 
	{ "CONNECTION_ENDP_BUILDER_VERSION_LBL", "API Version: " }, 
	{ "CONNECTION_ENDP_BUILDER_TITLE", "Endpoint URL Builder" }, 
	{ "CONNECTION_ENDP_BUILDER_HOSTNAME_DOMAIN_ERROR", "Hostname must end with zuora.com" }, 
	{ "CONNECTION_ENDP_BUILDER_VERSION_NUMBER_FORMAT_ERROR", "Version must be in numeric format" }, 
	{ "OPERATION_BUSINESS_OBJECT_HEADER", "Business Operations" }, 
	{ "OPERATION_ADD_CUSTOM_OPERATION_INTRO", "Select a zuora Cloud Operation." }, 
	{ "OPERATION_PAGE_HEADER", "Cloud Operation Configuration" }, 
	{ "OP_SOSL_AGGR_FUNC_NOT_SUPPORTED", "Error encountered parsing SOSL query statement. Aggregate functions are not supported in SOSL. Unexpected token found {0}" }, 
	{ "HEADER_PAGE_HEADER", "Header and Properties" }, 
	{ "OPERATION_HEADER_PROPERTIES_PAGE_LBL", "Select Header properties for selected zuora.com Cloud Operation" }, 
	{ "CONNECT_INTRO_PROMPT", "A zuora Cloud Server connection is required to access the operations and business objects available." }, 
	{ "APPLICATION_ID_LBL", "&Application ID:" }, 
	{ "APPLICATION_ID_TIP", "Enter Application Id for zuora connection" }, 
	{ "ENABLE_DESCRIBE_EVENTS", "EnableDescribe" }, 
	{ "ENABLE_DESCRIBE_TIP", "To enable Describe calls" }, 
	{ "COMMIT_AFTER_COLUMN", "Commit" }, 
	{ "PROCESSING_OPTIONS_HEADER", "zuora Processing Options" }, 
	{ "HEADERS", "zuora Headers" }, 
	{ "AllOrNone_Header_EVENTS", "AllOrNoneHeader" }, 
	{ "AllOrNone_Header_TIP", "zuora Transaction Handling" }, 
	{ "Truncation_Header_HEADER", "zuora Truncation Handling" }, 
	{ "Truncation_Header_EVENTS", "AllowFieldTruncationHeader" }, 
	{ "Truncation_Header_TIP", "Specifies the truncation behavior for some field types" }, 
	{ "AssignmentRule_Header_HEADER", "zuora Assignment Handling" }, 
	{ "ASSIGNMENT_RULE_ERROR", "You have selected Assignment Rule Header checkbox, Please provide the Assignment Rule ID in the provided text field!!!" }, 
	{ "AssignmentRule_Header_EVENTS", "AssignmentRuleHeader" }, 
	{ "AssignmentRule_Header_TIP", "Specifies the assignment rule to use" }, 
	{ "ASSIGNMENT_RULE_ID", "assignmentRuleId" }, 
	{ "ASSIGNMENT_RULE_RULE_ID_TIP", "The ID of a specific assignment rule to run for the Case or Lead. The assignment rule can be active or inactive. The ID can be retrieved by querying the AssignmentRule object. If specified, do not specify useDefaultRule. This element is ignored for accounts, because all territory assignment rules are applied." }, 
	{ "INVALID_WSDL", "Provided WSDL is not a valid zuora.com enterprise WSDL." }, 
	{ "ENTERPRISE_WSDL_IN_CUSTOM", "Provided WSDL is a zuora.com enterprise WSDL. Please provide custom WSDL" }, 
	{ "packageVersions_Header_HEADER", "zuora Package Version Handling" }, 
	{ "PACKAGE_VERSION_ERROR", "You have selected Packaged Version Header checkbox, Please provide the Packaged Version in the provided text field!!!" }, 
	{ "packageVersions_Header_EVENTS", "PackageVersionHeader" }, 
	{ "packageVersions_Header_TIP", "Specifies a version of an installed managed package in the format specified <majorNumber.minorNumber.namespace>" }, 
	{ "ASSIGNMENT_RULE_ERROR", "You have selected Assignment Rule Header checkbox, Please provide the Assignment Rule ID in the provided text field!!!" }, 
	{ "MruHeader_Header_HEADER", "zuora MruHeader Handling" }, 
	{ "MruHeader_EVENTS", "MruHeader" }, 
	{ "MruHeader_TIP", "Indicates whether to update the list of most recently used items" }, 
	{ "QueryOptions_Header_HEADER", "zuora QueryOptions Handling" }, 
	{ "OP_INVALID_WSDL_OPERATION_NAME_NUMERIC", "WSDL operation name should not start with numeric character." }, 
	{ "OP_INVALID_WSDL_OPERATION_NAME_SPL", "WSDL operation name should not contain special character." }, 
	{ "OP_INVALID_WSDL_OPERATION_NAME_TITLE", "Invalid WSDL operation name." }, 
	{ "QueryOptions_EVENTS", "QueryOptions" }, 
	{ "QueryOptions_TIP", "Specifies the batch size for query results. The default is 500; the minimum is 200, and the maximum is 2,000." }, 
	{ "INVALID_HEADER_QUERY_OPTIONS_VALUE_ERROR", "Invalid value for header : queryOptions. It should not exceed 2000." }, 
	{ "INVALID_HEADER_VALUE_ERROR_TITLE", "Invalid header value" }, 
	{ "INVALID_HEADER_DEBUG_LEVEL_VALUE_ERROR", "Invalid value for header : debugLevel. Debug level can be one of following : \n            NONE\n            DEBUGONLY\n            DB\n            PROFILING\n            CALLOUT\n            DETAIL" }, 
	{ "OP_INVALID_SOQL_ERROR_TITLE", "Invalid query statement." }, 
	{ "OP_INVALID_SOSL_ERROR_TITLE", "Invalid search statement." }, 
	{ "OP_INVALID_STRING_ERROR_TITLE", "Invalid statement." }, 
	{ "OP_OBJECT_NOT_QUERYABLE", "Error encountered parsing SOQL query statement. Object {0} is not queryable." }, 
	{ "OP_OBJECT_NOT_SEARCHABLE", "Error encountered parsing SOQL query statement. Object {0} is not searchable." }, 
	{ "OP_INVALID_STRING_WARNING_PROMPT", " Click 'Yes' to continue or 'No' to fix error" }, 
	{ "OP_OPERATION_FIRST_TAB_TEXT", "Operations Tab" }, 
	{ "OP_OPERATION_FIRST_TAB_TIP", "Select the operations" }, 
	{ "OP_OPERATION_SECOND_TAB_TEXT", "Header and Properties " }, 
	{ "OP_OPERATION_SECOND_TAB_TIP", "Headers and Property options for operation" }, 
	{ "QT_QUERY_TEST_TIP", "Run Query Test tool" }, 
	{ "ST_SEARCH_TEST_TIP", "Run Search Test tool" }, 
	{ "OP_QUERY_BUILDER_TIP", "Invoke Query Editor Tool" }, 
	{ "OP_SEARCH_BUILDER_TIP", "Invoke Search Editor Tool" }, 
	{ "ST_SEARCH_TEST_DIALOG_TITLE", "Search Test" }, 
	{ "QT_QUERY_TEST_DIALOG_TITLE", "Query Test" }, 
	{ "TEST_DONE_BUTTON", "&Done" }, 
	{ "TEST_SAVE_BUTTON", "&Save" }, 
	{ "ST_STATEMENT_LBL", "Search &Statement:" }, 
	{ "ST_STATEMENT_TIP", "Search Statement to be executed" }, 
	{ "ST_REFRESH_TIP", "Refresh Bind Parameters if Search Statement changed." }, 
	{ "ST_EXECUTE_TIP", "Execute Search" }, 
	{ "ST_BIND_PARAMETERS", "Bind Parameters:" }, 
	{ "ST_RETURN_COUNT_LBL", "Object Count:" }, 
	{ "ST_RESULT_TIP", "Output from search execution" }, 
	{ "ST_RESULT_LBL", "Results from {0}:" }, 
	{ "QT_STATEMENT_LBL", "Query &Statement:" }, 
	{ "QT_STATEMENT_TIP", "Query Statement to be executed" }, 
	{ "QT_REFRESH_TIP", "Refresh Bind Parameters if Query Statement changed." }, 
	{ "QT_EXECUTE_TIP", "Execute Query" }, 
	{ "QT_BIND_PARAMETERS", "Bind Parameters:" }, 
	{ "QT_RETURN_COUNT_LBL", "Object Count:" }, 
	{ "QT_RESULT_TIP", "Output from Query execution" }, 
	{ "QT_RESULT_LBL", "Results from {0}:" }, 
	{ "QT_INTRO_TXT", "Enter a value for each bind parameter and then execute query. After testing, if you've modified the query Statement, you may hit Save to retain the new statement.  Otherwise, hit Done." }, 
	{ "ST_INTRO_TXT", "Enter a value for each bind parameter and then execute search. After testing, if you've modified the Search Statement, you may hit Save to retain the new statement.  Otherwise, hit Done." }, 
	{ "PARAMETER_VALUE_LBL", "{0} Value:" }, 
	{ "PARAM_VALUE_TIP", "Parameter value for :{0}" }, 
	{ "BIND_VARIABLE_ERROR_TITLE", "Bind Variable Error" }, 
	{ "UNBOUND_VARIABLE_ERROR", "The Statement contains the bind variable {0} which has not been bound. Hit the Refresh button to see all bind parameters needed." }, 
	{ "EXECUTE_STATUS_WAIT", "Please wait..." }, 
	{ "EXECUTE_STATUS_DETAIL", "Executing request..." }, 
	{ "ST_EXECUTE_QUERY_EXCEPTION", "The search execution raised the following exception: \n{0}" }, 
	{ "OP_INVALID_SELECT_ERROR", "Error encountered parsing SOQL query statement. Query does not start with SELECT." }, 
	{ "OP_INVALID_FROM_ERROR", "Error encountered parsing SOQL query statement. Query does not contain FROM." }, 
	{ "OP_INVALID_WHEN_ERROR", "Error encountered parsing SOQL query statement. Query does not contain WHEN." }, 
	{ "OP_INVALID_ELSE_ERROR", "Error encountered parsing SOQL query statement. Query does not contain ELSE." }, 
	{ "OP_INVALID_END_ERROR", "Error encountered parsing SOQL query statement. Query does not contain END." }, 
	{ "OP_EMPTY_FIELDS_AFTER_SELECT_ERROR", "Error encountered parsing SOQL query statement. Query does not contain any fields after SELECT." }, 
	{ "OP_EMPTY_OBJECT_ERROR", "Error encountered parsing SOQL query statement.The business object name should be given after FROM." }, 
	{ "OP_INVALID_OBJECT_ERROR", "Error encountered parsing the statement. A business object with the name {0} cannot be found in zuora." }, 
	{ "OP_INVALID_INNER_DRIVING_OBJECT", "Error encountered parsing the statement. First sObject of a nested query must be a child of its root query." }, 
	{ "OP_INVALID_CHILD_OBJECT", "Error encountered parsing the statement. Table {0} does not have any relation with driving object" }, 
	{ "OP_INVALID_RELATED_TABLE", "Error encountered parsing the statement. No related table found for {0} in zuora." }, 
	{ "OP_QUERY_RELATIONSHIP_NOT_IN_CACHE", "Error encountered parsing the statement. Metadata to validate {0} relation is not available in cache." }, 
	{ "OP_QUERY_RELATIONSHIP_NOT_SUPPORTED_IN_OFFLINE", "Error encountered parsing the statement. Relationship queries are not supported in offline mode." }, 
	{ "OP_QUERY_MISSING_KEYWORD", "Error encountered parsing the statement. Missing keyword : {0}" }, 
	{ "OP_QUERY_DUPLICATE_FIELD", "Error encountered parsing the statement. Duplicate field : {0}" }, 
	{ "OP_QUERY_TYPEOF_WHO_WHAT_OWNER", "Error encountered parsing the statement. Only WHO/WHAT/OWNER keywords are allowed after TYPEOF keyword" }, 
	{ "OP_INNER_QUERY_MAX_LEVEL", "Error encountered parsing the statement. Statements cannot query aggregate relationships more than 1 level away from the root entity object." }, 
	{ "OP_QUERY_ALIAS_ERROR", "Error encountered parsing the statement. Only aggregate expressions can use field aliasing" }, 
	{ "OP_INNER_QUERY_AGGR_EXPR", "Error encountered parsing the statement. Only root queries support aggregate expressions" }, 
	{ "OP_INNER_QUERY_TYPEOF", "Error encountered parsing the statement. TYPEOF is not allowed in the SELECT clause of inner query." }, 
	{ "OP_INNER_QUERY_COUNT()", "Error encountered parsing the statement. COUNT() can only be used with root queries" }, 
	{ "OP_QUERY_INVALID_TOKEN_FOUND", "Error encountered parsing the statement. Found unexpected token: {0}" }, 
	{ "OP_QUERY_END_FROM_ERROR", "Error encountered parsing SOQL query statement. 'END' expected before 'FROM' " }, 
	{ "OP_INVALID_MULTI_DRIVING_OBJECT_ERROR", "{0} must have relation with the driving SObject {1}" }, 
	{ "OP_INVALID_FIELD_ERROR", "Error encountered parsing query statement. A field named {0} is not defined in object {1} in zuora." }, 
	{ "OP_BLANK_FIELD_ERROR", "Error encountered parsing query statement. Field name is missing for object {0}." }, 
	{ "OP_NO_CRITERIA_AFTER_WHERE_ERROR", "Error encountered parsing query statement. Query does not contain any criteria after WHERE." }, 
	{ "OP_INVALID_CHILD_OBJECT_ERROR", "Error encountered parsing SOQL query statement. The child object must be suffixed with 's'." }, 
	{ "OP_EMPTY_INNER_QUERY_ERROR", "Error encountered parsing SOQL query statement. Query contains empty inner query." }, 
	{ "OP_INVALID_FIND_ERROR", "Error encountered parsing SOSL search statement. Search does not start with FIND." }, 
	{ "OP_WITHOUT_BRACES_ERROR", "Error encountered parsing SOSL search statement. The search term must be enclosed in braces." }, 
	{ "OP_WITHOUT_RETURNING_ERROR", "Error encountered parsing SOSL search statement. The search term must contain RETURNING keyword." }, 
	{ "OP_INVALID_CRITERIA_AFTER_IN_ERROR", "Error encountered parsing SOSL search statement. The search should contain some criteria after IN." }, 
	{ "OP_INVALID_CRITERIA_AFTER_RETURNING_ERROR", "Error encountered parsing SOSL search statement. The search should contain some criteria after RETURNING." }, 
	{ "OP_INVALID_SEARCH_TERM_ERROR", "Error encountered parsing SOSL search statement. The search term must be longer than one character." }, 
	{ "OP_INVALID_IN_FIELDS_GROUP_ERROR", "Error encountered parsing SOSL search statement. The IN fields group is invalid. You can enter one of the following fields group:ALL FIELDS, EMAIL FIELDS, NAME FIELDS, PHONE FIELDS, SIDEBAR FIELDS" }, 
	{ "OP_MISSING_BRACKET_ERROR", "Error encountered parsing the statement. Brackets not closed properly." }, 
	{ "OP_INVALID_TOKEN_BEFORE_IN_ERROR", "Error encountered parsing SOSL Search statement. Statement contains malformed token before IN." }, 
	{ "OP_MALFORMED_TOKEN_RETURNING_ERROR", "Error encountered parsing SOSL Search statement. MALFORMED_TOKEN:RETURNING." }, 
	{ "OP_QUERY_BATCH_SIZE_BLANK_ERROR", "You have checked the QueryOptionHeader, but didn't provide the Query Batch Size in the text field." }, 
	{ "OP_ASSIGMENT_RULE_ID_BLANK_ERROR", "You have checked the AssignmentRuleHeader, but didn't provide the AssignmentRuleId in the text field." }, 
	{ "OP_PACKAGE_VERSION_BLANK_ERROR", "You have checked the PackageVersionHeader, but didn't provide the PackageVersion (majorNo.minorNo.nameSpace) in the text field." }, 
	{ "OP_PACKAGE_VERSION_INVALID_FORMAT_ERROR", "Enter PackageVersion value in the PackageVersion in the format (majorNo.minorNo.nameSpace)." }, 
	{ "FINISH_PROMPT", "You have finished defining the zuora Cloud Adapter Reference : {0}" }, 
	{ "FINISH_SUMMARY", "When you click Finish, the wizard will create the {0} file in your project WSDLs directory. " }, 
	{ "FINISH_UPDATE_PROMPT", "You have finished updating the zuora Cloud Adapter Reference : {0}" }, 
	{ "FINISH_UPDATE_SUMMARY", "\nWhen you click Finish, the wizard will update the {0} file in your project WSDLs directory. " }, 
	{ "ApiQueryFault", "The row and column numbers where the problem occurred." }, 
	{ "LoginFault", "An error occurred during the login() call." }, 
	{ "InvalidSObjectFault", "An invalid sObject in a describeSObject(), describeSObjects(), describeLayout(), describeDataCategoryGroups(), describeDataCategoryGroupStructures(), create(), update(), retrieve(), or query() call." }, 
	{ "InvalidFieldFault", "An invalid field in a retrieve() or query() call." }, 
	{ "MalformedQueryFault", "A problem in the queryString passed in a query() call." }, 
	{ "CU_SERVICE_TYPE", "SAP Adapter" }, 
	{ "InvalidQueryLocatorFault", "A problem in the queryLocator passed in a queryMore() call." }, 
	{ "InvalidIdFault", "A specified ID was invalid in a setPassword() or resetPassword() call." }, 
	{ "UnexpectedErrorFault", "An unexpected error occurred. The error is not associated with any other API fault." }, 
	{ "API_CURRENTLY_DISABLED", "Because of a system problem, API functionality is temporarily unavailable." }, 
	{ "API_DISABLED_FOR_ORG", "API access has not been enabled for the organization. Contact zuora.com to enable API access." }, 
	{ "CANT_ADD_STANDARD_PORTAL_USER_TO_TERRITORY", "A user with a standard portal license can't be added to a territory." }, 
	{ "CIRCULAR_OBJECT_GRAPH", "The request failed because it contained a circular object reference." }, 
	{ "CLIENT_NOT_ACCESSIBLE_FOR_USER", "The current user does not have permission to access the specified client." }, 
	{ "CLIENT_REQUIRE_UPDATE_FOR_USER", "The current user is required to use a newer version of the specified client, and will have access until the client is updated." }, 
	{ "DELETE_REQUIRED_ON_CASCADE", "The delete operation triggers a cascade delete on a record, but the logged-in user does not have delete permission on that related object." }, 
	{ "DUPLICATE_COMM_NICKNAME", "You can't create a user with the same community nickname as another user." }, 
	{ "DUPLICATE_VALUE", "You can't supply a duplicate value for a field that must be unique. For example, you may have submitted two copies of the same session ID in a invalidateSessions() call." }, 
	{ "EXCEEDED_ID_LIMIT", "Too many IDs were specified in a call." }, 
	{ "EXCEEDED_LEAD_CONVERT_LIMIT", "Too many IDs were sent to a convertLead() call." }, 
	{ "EXCEEDED_MAX_SIZE_REQUEST", "The size of the message sent to the API exceeded 50 MB." }, 
	{ "EXCEEDED_MAX_TYPES_LIMIT", "The number of object types to describe is too large." }, 
	{ "EXCEEDED_QUOTA", "The size limit for organization data storage was exceeded during a create() call." }, 
	{ "FUNCTIONALITY_NOT_ENABLED", "Functionality has been temporarily disabled. Other calls may continue to work." }, 
	{ "INACTIVE_OWNER_OR_USER", "The user or record owner is not active." }, 
	{ "INACTIVE_PORTAL", "The referenced portal is inactive." }, 
	{ "INSUFFICIENT_ACCESS", "The user does not have sufficient access to perform the operation." }, 
	{ "INVALID_ASSIGNMENT_RULE", "An invalid AssignmentRuleHeader value was specified." }, 
	{ "INVALID_BATCH_SIZE", "The query options have an invalid batch size value." }, 
	{ "INVALID_CLIENT", "The client is invalid." }, 
	{ "INVALID_CROSS_REFERENCE_KEY", "An invalid foreign key can't be set on a field." }, 
	{ "INVALID_FIELD", "The specified field name is invalid." }, 
	{ "INVALID_FILTER_LANGUAGE", "The specified language can't be used as a filter." }, 
	{ "INVALID_FILTER_VALUE", "A SOQL query with LIKE specified an invalid character, for example, an incorrectly placed asterisk (*). Correct the query and resubmit." }, 
	{ "INVALID_ID_FIELD", "The specified ID is correctly formatted, but is not valid, for example, it is an ID of the wrong type, or the object it identifies no longer exists." }, 
	{ "INVALID_GOOGLE_DOCS_URL", "An invalid zuora record URL was used when trying to associate a Google Doc to that record. Correct the URL before trying the operation again." }, 
	{ "INVALID_LOCATOR", "The locator is invalid." }, 
	{ "INVALID_LOGIN", "The login() credentials are not valid, or the maximum number of logins have been exceeded. Contact your administrator for more information." }, 
	{ "INVALID_NEW_PASSWORD", "The new password does not conform with the password policies of the organization." }, 
	{ "INVALID_OPERATION", "The client application tried to submit an object that is already in process as part of workflow approval or processing." }, 
	{ "INVALID_OPERATION_WITH_EXPIRED_PASSWORD", "Due to password expiration, a valid password must be set using setPassword() before the call can be invoked." }, 
	{ "INVALID_QUERY_FILTER_OPERATOR", "An invalid operator was used in the query() filter clause, at least for that field." }, 
	{ "INVALID_QUERY_LOCATOR", "An invalid queryLocator parameter was specified in a queryMore() call. It is also possible that you've exceed the maximum number of calls, which is ten per user for the API, and five for Apex and Visualforce." }, 
	{ "INVALID_QUERY_SCOPE", "The specified search scope is invalid." }, 
	{ "INVALID_REPLICATION_DATE", "The date for replication is out of the allowed range, such as before the organization was created." }, 
	{ "INVALID_SETUP_OWNER", "The setup owner must be an Organization, Profile, or User." }, 
	{ "INVALID_SEARCH", "The search() call has invalid syntax or grammar. For more information, see the zuora SOQL and SOSL Reference Guide." }, 
	{ "INVALID_SEARCH_SCOPE", "The specified search scope is invalid." }, 
	{ "INVALID_SESSION_ID", "The specified sessionId is malformed (incorrect length or format) or has expired. Log in again to start a new session." }, 
	{ "INVALID_SOAP_HEADER", "There is an error in the SOAP header. If you are migrating from an earlier version of the API, be advised that the SaveOptions header can't be used with API version 6.0 or later. Use AssignmentRuleHeader instead." }, 
	{ "INVALID_SSO_GATEWAY_URL", "The URL provided to configure the Single Sign-On gateway was not a valid URL." }, 
	{ "INVALID_TYPE", "The specified sObject type is invalid." }, 
	{ "INVALID_TYPE_FOR_OPERATION", "The specified sObject type is invalid for the specified operation." }, 
	{ "LIMIT_EXCEEDED", "An array is too long. For example, there are too many BCC addresses, targets, or email messages." }, 
	{ "LOGIN_DURING_RESTRICTED_DOMAIN", "The user is not allowed to log in from this IP address." }, 
	{ "LOGIN_DURING_RESTRICTED_TIME", "The user is not allowed to log in during this time period." }, 
	{ "MALFORMED_ID", "An invalid ID string was specified. For information about IDs, see ID Field Type." }, 
	{ "MALFORMED_QUERY", "An invalid query string was specified. For example, the query string was longer than 10,000 characters." }, 
	{ "MALFORMED_SEARCH", "An invalid search string was specified. For example, the search string was longer than 10,000 characters." }, 
	{ "MISSING_ARGUMENT", "A required argument is missing." }, 
	{ "MIXED_DML_OPERATION", "There are limits on what kinds of DML operations can be performed in the same transaction. For more information, see the Force.com Apex Code Developer's Guide." }, 
	{ "NOT_MODIFIED", "The describe call response has not changed since the specified date." }, 
	{ "NO_SOFTPHONE_LAYOUT", "If an organization has the CTI feature enabled, but no softphone layout has been defined, this exception is returned if a describe call is issued. This is most often caused because no call center has been defined: during call center definition, a default softphone layout is created. If an organization does not have the CTI feature enabled, FUNCTIONALITY_NOT_ENABLED is returned instead." }, 
	{ "NUMBER_OUTSIDE_VALID_RANGE", "The number specified is outside the valid range for the field." }, 
	{ "OPERATION_TOO_LARGE", "The query has returned too many results. If certain queries are run by a user without the \"View All Data\" permission and many records are returned, those queries would require sharing rule checking. An example of this would be queries that are run on objects, such as Task, that use a polymorphic foreign key. Such queries return this exception because the operation requires too many resources. To correct, add filters to the query to narrow the scope, or use filters such as date ranges to break the query up into a series of smaller queries." }, 
	{ "ORG_LOCKED", "The organization has been locked. You must contact zuora.com to unlock the organization." }, 
	{ "ORG_NOT_OWNED_BY_INSTANCE", "The user tried to log in to the wrong server instance. Choose another server instance or log in at https://login.zuora.com. You can use http instead of https." }, 
	{ "PASSWORD_LOCKOUT", "The user has exceeded the allowed number of login attempts. The user must contact his or her administrator to regain login access." }, 
	{ "PORTAL_NO_ACCESS", "Access to the specified portal is not available." }, 
	{ "QUERY_TIMEOUT", "The query has timed out. For more information, see the zuora SOQL and SOSL Reference Guide." }, 
	{ "QUERY_TOO_COMPLICATED", "SOQL query is either selecting too many fields or there are too many filter conditions. Try reducing the number of formula fields referenced in the query." }, 
	{ "REQUEST_LIMIT_EXCEEDED", "Exceeded either the concurrent request limit or the request rate limit for your organization. For details on API request limits, see API Usage Metering." }, 
	{ "REQUEST_RUNNING_TOO_LONG", "A request has taken too long to be processed." }, 
	{ "SERVER_UNAVAILABLE", "A server that is necessary for this call is currently unavailable. Other types of requests might still work." }, 
	{ "SSO_SERVICE_DOWN", "The service was unavailable, and an authentication call to the organization's specified Single Sign-On server failed." }, 
	{ "TOO_MANY_APEX_REQUESTS", "Too many Apex requests have been issued. If this persists, contact zuora Customer Support." }, 
	{ "TRIAL_EXPIRED", "The trial period for the organization has expired. A representative from the organization must contact zuora.com to re-enable the organization." }, 
	{ "UNSUPPORTED_API_VERSION", "Invalid Api version specified on URL." }, 
	{ "UNSUPPORTED_CLIENT", "This version of the client is no longer supported." }, 
	{ "ALL_OR_NONE_OPERATION_ROLLED_BACK", "The bulk operation was rolled back because one of the records wasn't processed successfully. See AllOrNoneHeader." }, 
	{ "ALREADY_IN_PROCESS", "You can't submit a record that is already in an approval process. You must wait for the previous approval process to complete before resubmitting a request with this record." }, 
	{ "ASSIGNEE_TYPE_REQUIRED", "You must designate an assignee for any workflow task (ProcessInstance, ProcessInstanceStep, or ProcessInstanceWorkitem)." }, 
	{ "BAD_CUSTOM_ENTITY_PARENT_DOMAIN", "The changes you are trying to make can't be completed because changes to the associated master-detail relationships can't be made." }, 
	{ "CANNOT_CASCADE_PRODUCT_ACTIVE", "An update to a product caused by a cascade can't be done because the associated product is active." }, 
	{ "CANNOT_CHANGE_FIELD_TYPE_OF_APEX_REFERENCED_FIELD", "You can't change the type of a field that is referenced in an Apex script." }, 
	{ "CANNOT_CREATE_ANOTHER_MANAGED_PACKAGE", "You can only create one managed package in an organization." }, 
	{ "CANNOT_DEACTIVATE_DIVISION", "You can't deactivate Divisions if an assignment rule references divisions or if the DefaultDivision field on a user record isn't set to null." }, 
	{ "CANNOT_DELETE_LAST_DATED_CONVERSION_RATE", "You must have at least one DatedConversionRate record if dated conversions are enabled." }, 
	{ "CANNOT_DELETE_MANAGED_OBJECT", "You can't modify components that are included in a managed package." }, 
	{ "CANNOT_DISABLE_LAST_ADMIN", "You must have at least one active administrator user." }, 
	{ "CANNOT_ENABLE_IP_RESTRICT_REQUESTS", "If you exceed the limit of five IP ranges specified in a profile, you can't enable restriction of login by IP addresses. Reduce the number of specified ranges in the profile and try the request again." }, 
	{ "CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY", "You do not have permission to create, update, or activate the specified record." }, 
	{ "CANNOT_MODIFY_MANAGED_OBJECT", "You can't modify components that are included in a managed package." }, 
	{ "CANNOT_RENAME_APEX_REFERENCED_FIELD", "You can't rename a field that is referenced in an Apex script." }, 
	{ "CANNOT_RENAME_APEX_REFERENCED_OBJECT", "You can't rename an object that is referenced in an Apex script." }, 
	{ "CANNOT_REPARENT_RECORD", "You can't define a new parent record for the specified record." }, 
	{ "CANNOT_RESOLVE_NAME", "A sendEmail() call could not resolve an object name." }, 
	{ "CANNOT_UPDATE_CONVERTED_LEAD", "A converted lead could not be updated." }, 
	{ "CANT_DISABLE_CORP_CURRENCY", "You can't disable the corporate currency for an organization. To disable a currency that is set as the corporate currency, first use the user interface to change the corporate currency to a different currency, and then disable the original currency." }, 
	{ "CANT_UNSET_CORP_CURRENCY", "You can't change the corporate currency for an organization from the API. Use the user interface to change the corporate currency." }, 
	{ "CHILD_SHARE_FAILS_PARENT", "You can't change the owner of or define sharing rules for a record that is a child of another record if you do not also have the appropriate permissions on the parent. For example, you can't change the owner of a contact record if you can't edit its parent account record." }, 
	{ "CIRCULAR_DEPENDENCY", "You can't create a circular dependency between metadata objects in your organization. For example, public group A can't include public group B, if public group B already includes public group A." }, 
	{ "COMMUNITY_NOT_ACCESSIBLE", "You do not have permission to access the community that this entity belongs to. You must be given permission to access the community before you can access this entity." }, 
	{ "CUSTOM_CLOB_FIELD_LIMIT_EXCEEDED", "You can't exceed the maximum size for a CLOB field." }, 
	{ "CUSTOM_ENTITY_OR_FIELD_LIMIT", "You have reached the maximum number of custom objects or custom fields for your organization." }, 
	{ "CUSTOM_FIELD_INDEX_LIMIT_EXCEEDED", "You have reached the maximum number of indexes on a field for your organization." }, 
	{ "CUSTOM_INDEX_EXISTS", "You can create only one custom index per field." }, 
	{ "CUSTOM_LINK_LIMIT_EXCEEDED", "You have reached the maximum number of custom links for your organization." }, 
	{ "CUSTOM_TAB_LIMIT_EXCEEDED", "You have reached the maximum number of custom tabs for your organization." }, 
	{ "DELETE_FAILED", "You can't delete a record because it is in use by another object." }, 
	{ "DEPENDENCY_EXISTS", "You can't perform the requested operation because of an existing dependency on the specified object or field." }, 
	{ "DUPLICATE_CASE_SOLUTION", "You can't create a relationship between the specified case and solution because it already exists." }, 
	{ "DUPLICATE_CUSTOM_ENTITY_DEFINITION", "Custom object or custom field IDs must be unique." }, 
	{ "DUPLICATE_CUSTOM_TAB_MOTIF", "You can't create a custom object or custom field with a duplicate master name." }, 
	{ "DUPLICATE_DEVELOPER_NAME", "You can't create a custom object or custom field with a duplicate developer name." }, 
	{ "DUPLICATE_EXTERNAL_ID", "A user-specified external ID matches more than one record during an upsert." }, 
	{ "DUPLICATE_MASTER_LABEL", "You can't create a custom object or custom field with a duplicate master name." }, 
	{ "DUPLICATE_SENDER_DISPLAY_NAME", "A sendEmail() call could not choose between OrgWideEmailAddress.DisplayName or senderDisplayName. Define only one of the two fields." }, 
	{ "DUPLICATE_USERNAME", "A create, update, or upsert failed because of a duplicate user name." }, 
	{ "DUPLICATE_VALUE", "You can't supply a duplicate value for a field that must be unique. For example, you may have submitted two copies of the same session ID in a invalidateSessions() call." }, 
	{ "EMAIL_NOT_PROCESSED_DUE_TO_PRIOR_ERROR", "Because of an error earlier in the call, the current email was not processed." }, 
	{ "EMPTY_SCONTROL_FILE_NAME", "The Scontrol file name was empty, but the binary was not empty." }, 
	{ "ENTITY_FAILED_IFLASTMODIFIED_ON_UPDATE", "You can't update a record if the date inLastModifiedDate is later than the current date." }, 
	{ "ENTITY_IS_ARCHIVED", "You can't access a record if it has been archived." }, 
	{ "ENTITY_IS_DELETED", "You can't reference an object that has been deleted. Note that this status code only occurs in version 10.0 of the API and later. Previous releases of the API use INVALID_ID_FIELD for this error." }, 
	{ "ENTITY_IS_LOCKED", "You can't edit a locked object during a workflow processing operation." }, 
	{ "ERROR_IN_MAILER", "An email address is invalid, or another error occurred during an email-related transaction." }, 
	{ "FAILED_ACTIVATION", "The activation of a Contract failed." }, 
	{ "FIELD_CUSTOM_VALIDATION_EXCEPTION", "You can't define a custom validation formula that violates a field integrity rule." }, 
	{ "FIELD_FILTER_VALIDATION_EXCEPTION", "You can't violate field integrity rules." }, 
	{ "FILTERED_LOOKUP_LIMIT_EXCEEDED", "The creation of the lookup filter failed because it exceeds the maximum number of lookup filters allowed per object." }, 
	{ "HTML_FILE_UPLOAD_NOT_ALLOWED", "Your attempt to upload an HTML file failed. HTML attachments and documents, including HTML attachments to a Solution, can't be uploaded if the Disallow HTML documents and attachments checkbox is selected in Your Name > Setup > Security Controls > HTML Documents and Attachments Settings." }, 
	{ "IMAGE_TOO_LARGE", "The image exceeds the maximum width, height, and file size." }, 
	{ "INACTIVE_OWNER_OR_USER", "The owner of the specified item is an inactive user. To reference this item, either reactivate the owner or reassign ownership to another active user." }, 
	{ "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY", "An operation affects an object that is cross-referenced by the specified object, but the logged-in user does not have sufficient permissions on the cross-referenced object. For example, if the logged-in user attempts to modify an account record, that user might not have permission to approve, reject, or reassign a ProcessInstanceWorkitem that is submitted after that action." }, 
	{ "INSUFFICIENT_ACCESS_OR_READONLY", "You can't perform the specified action because you do not have sufficient permissions." }, 
	{ "INVALID_ACCESS_LEVEL", "You can't define a new sharing rule if it provides less access than the specified organization-wide default." }, 
	{ "INVALID_ARGUMENT_TYPE", "You supplied an argument that is of the wrong type for the operation being attempted." }, 
	{ "INVALID_ASSIGNEE_TYPE", "You specified an assignee type that is not a valid integer between one and six." }, 
	{ "INVALID_ASSIGNMENT_RULE", "You specified an assignment rule that is invalid or that is not defined in the organization." }, 
	{ "INVALID_BATCH_OPERATION", "The specified batch operation is invalid." }, 
	{ "INVALID_CONTENT_TYPE", "The outgoing email has anEmailFileAttachment with an invalidcontentType property. See RFC2045 - Internet Message Format." }, 
	{ "INVALID_CREDIT_CARD_INFO", "The specified credit card information is not valid." }, 
	{ "INVALID_CROSS_REFERENCE_KEY", "The specified value in a relationship field is not valid, or data is not of the expected type." }, 
	{ "INVALID_CROSS_REFERENCE_TYPE_FOR_FIELD", "The specified cross reference type is not valid for the specified field." }, 
	{ "INVALID_CURRENCY_CONV_RATE", "You must specify a positive, non-zero value for the currency conversion rate." }, 
	{ "INVALID_CURRENCY_CORP_RATE", "You can't modify the corporate currency conversion rate." }, 
	{ "INVALID_CURRENCY_ISO", "The specified currency ISO code is not valid.." }, 
	{ "INVALID_EMAIL_ADDRESS", "A specified email address is invalid." }, 
	{ "INVALID_EMPTY_KEY_OWNER", "You can't set the value for owner to null." }, 
	{ "INVALID_FIELD", "You specified an invalid field name when trying to update or upsert a record." }, 
	{ "INVALID_FIELD_FOR_INSERT_UPDATE", "You can't combine a person account record type change with any other field update." }, 
	{ "INVALID_FIELD_WHEN_USING_TEMPLATE", "You can't use an email template with an invalid field name." }, 
	{ "INVALID_FILTER_ACTION", "The specified filter action can't be used with the specified object. For example, an alert is not a valid filter action for a Task." }, 
	{ "INVALID_ID_FIELD", "The specified ID field (ID, ownerId), or cross-reference field is invalid." }, 
	{ "INVALID_INET_ADDRESS", "A specified Inet address is not valid." }, 
	{ "INVALID_LINEITEM_CLONE_STATE", "You can't clone a Pricebook2 or PricebookEntry record if those objects are not active." }, 
	{ "INVALID_MASTER_OR_TRANSLATED_SOLUTION", "The solution is invalid. For example, this error can occur if you try to associate a translated solution with a master solution when another translated solution in the same language is already associated with the master solution." }, 
	{ "INVALID_MESSAGE_ID_REFERENCE", "The outgoing email's References or In-Reply-To fields are invalid. These fields must contain valid Message-IDs. See RFC2822 - Internet Message Format." }, 
	{ "INVALID_OPERATION", "There is no applicable approval process for the specified object." }, 
	{ "INVALID_OPERATOR", "The specified operator is not applicable for the field type when used as a workflow filter." }, 
	{ "INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST", "You specified an invalid or null value for a restricted picklist." }, 
	{ "INVALID_PARTNER_NETWORK_STATUS", "The specified partner network status is invalid for the specified template field." }, 
	{ "INVALID_PERSON_ACCOUNT_OPERATION", "You can't delete a person account." }, 
	{ "INVALID_READ_ONLY_USER_DML", "You can't create, update, or delete data while the instance where your organization resides is being upgraded to the latest release. Please try again after the release has completed. For release schedules, see trust.zuora.com." }, 
	{ "INVALID_SAVE_AS_ACTIVITY_FLAG", "You must specify true or false for the saveAsActivity flag." }, 
	{ "INVALID_SESSION_ID", "The specified sessionId is malformed (incorrect length or format) or has expired. Log in again to start a new session." }, 
	{ "INVALID_STATUS", "The specified organization status change is not valid." }, 
	{ "INVALID_TYPE", "The specified type is not valid for the specified object." }, 
	{ "INVALID_TYPE_FOR_OPERATION", "The specified type is not valid for the specified operation." }, 
	{ "INVALID_TYPE_ON_FIELD_IN_RECORD", "The specified value is not valid for the specified field's type." }, 
	{ "IP_RANGE_LIMIT_EXCEEDED", "The specified IP address is outside the IP range specified for the organization." }, 
	{ "LICENSE_LIMIT_EXCEEDED", "You have exceeded the number of licenses assigned to your organization." }, 
	{ "LIGHT_PORTAL_USER_EXCEPTION", "You attempted an action with a high-volume portal user that's not allowed. For example, trying to add the user to a case team." }, 
	{ "LIMIT_EXCEEDED", "You have exceeded a limit. The limit may be on a field size or value, license, or other component." }, 
	{ "LOGIN_CHALLENGE_ISSUED", "An email containing a security token was sent to the user's email address because he or she logged in from an IP address that is not included in their organization's list of trusted IP addresses. The user can't log in until he or she adds the security token to the end of his or her password." }, 
	{ "LOGIN_CHALLENGE_PENDING", "The user logged in from an IP address that is not included in their organization's list of trusted IP addresses, but a security token has not yet been issued." }, 
	{ "LOGIN_MUST_USE_SECURITY_TOKEN", "The user must add a security token to the end of his or her password to log in." }, 
	{ "MALFORMED_ID", "An ID must be either 15 characters, or 18 characters with a valid case-insensitive extension. There is also an exception code of the same name." }, 
	{ "MANAGER_NOT_DEFINED", "A manager has not been defined for the specified approval process." }, 
	{ "MASSMAIL_RETRY_LIMIT_EXCEEDED", "A mass mail retry failed because your organization has exceeded its mass mail retry limit." }, 
	{ "MASS_MAIL_LIMIT_EXCEEDED", "The organization has exceeded its daily limit for mass email. Mass email messages can't be sent again until the next day." }, 
	{ "MAXIMUM_CCEMAILS_EXCEEDED", "You have exceeded the maximum number of specified CC addresses in a workflow alert." }, 
	{ "MAXIMUM_DASHBOARD_COMPONENTS_EXCEEDED", "You have exceeded the document size limit for a dashboard." }, 
	{ "MAXIMUM_HIERARCHY_LEVELS_REACHED", "You have reached the maximum number of levels in a hierarchy." }, 
	{ "MAXIMUM_SIZE_OF_ATTACHMENT", "You have exceeded the maximum size of an attachment." }, 
	{ "MAXIMUM_SIZE_OF_DOCUMENT", "You have exceeded the maximum size of a document." }, 
	{ "MAX_ACTIONS_PER_RULE_EXCEEDED", "You have exceeded the maximum number of actions per rule." }, 
	{ "MAX_ACTIVE_RULES_EXCEEDED", "You have exceeded the maximum number of active rules." }, 
	{ "MAX_APPROVAL_STEPS_EXCEEDED", "You have exceeded the maximum number of approval steps for an approval process." }, 
	{ "MAX_FORMULAS_PER_RULE_EXCEEDED", "You have exceeded the maximum number of formulas per rule." }, 
	{ "MAX_RULES_EXCEEDED", "You have exceeded the maximum number of rules for an object." }, 
	{ "MAX_RULE_ENTRIES_EXCEEDED", "You have exceeded the maximum number of entries for a rule." }, 
	{ "MAX_TASK_DESCRIPTION_EXCEEDED", "The task description is too long." }, 
	{ "MAX_TM_RULES_EXCEEDED", "You have exceeded the maximum number of rules per Territory." }, 
	{ "MAX_TM_RULE_ITEMS_EXCEEDED", "You have exceeded the maximum number of rule criteria per rule for a Territory." }, 
	{ "MERGE_FAILED", "A merge operation failed." }, 
	{ "MISSING_ARGUMENT", "You did not specify a required argument." }, 
	{ "NONUNIQUE_SHIPPING_ADDRESS", "You can't insert a reduction order item if the original order shipping address is different from the shipping address of other items in the reduction order." }, 
	{ "NO_APPLICABLE_PROCESS", "A process() request failed because the record submitted does not satisfy the entry criteria of any workflow process for which the user has permission." }, 
	{ "NO_ATTACHMENT_PERMISSION", "Your organization does not permit email attachments." }, 
	{ "NO_INACTIVE_DIVISION_MEMBERS", "You can't add members to an inactive Division." }, 
	{ "NO_MASS_MAIL_PERMISSION", "You do not have permission to send the specified email. You must have \"Mass Email\" if you are sending mass mail or \"Send Email\" if you are sending individual email." }, 
	{ "NUMBER_OUTSIDE_VALID_RANGE", "The number specified is outside the valid range of values." }, 
	{ "NUM_HISTORY_FIELDS_BY_SOBJECT_EXCEEDED", "The number of history fields specified for the sObject exceeds the allowed limit." }, 
	{ "OP_WITH_INVALID_USER_TYPE_EXCEPTION", "The operation you attempted can't be performed for one or more users. For example, you can't add high-volume portal users to a group." }, 
	{ "OPTED_OUT_OF_MASS_MAIL", "An email can't be sent because the specified User has opted out of mass mail." }, 
	{ "PACKAGE_LICENSE_REQUIRED", "The logged-in user can't access an object that is in a licensed package if the logged-in user does not have a license for the package." }, 
	{ "PORTAL_USER_ALREADY_EXISTS_FOR_CONTACT", "A create User operation failed because you can't create a second portal user under a Contact." }, 
	{ "PRIVATE_CONTACT_ON_ASSET", "You can't have a private contact on an asset." }, 
	{ "RECORD_IN_USE_BY_WORKFLOW", "You can't access a record if it is currently in use by a workflow process." }, 
	{ "REQUEST_RUNNING_TOO_LONG", "A request that has been running too long may be canceled." }, 
	{ "REQUIRED_FIELD_MISSING", "A call requires a field that was not specified." }, 
	{ "SHARE_NEEDED_FOR_CHILD_OWNER", "You can't delete a sharing rule for a parent record if its child record needs it." }, 
	{ "SINGLE_EMAIL_LIMIT_EXCEEDED", "The organization has exceeded its daily limit for single emails. Single email messages can't be sent again until the next day." }, 
	{ "STANDARD_PRICE_NOT_DEFINED", "Custom prices can't be defined without corresponding standard prices." }, 
	{ "STORAGE_LIMIT_EXCEEDED", "You have exceeded your organization's storage limit." }, 
	{ "STRING_TOO_LONG", "The specified string exceeds the maximum allowed length." }, 
	{ "TABSET_LIMIT_EXCEEDED", "You have exceeded the number of tabs allowed for a tabset." }, 
	{ "TEMPLATE_NOT_ACTIVE", "The template specified is unavailable. Specify another template or make the template available for use." }, 
	{ "TERRITORY_REALIGN_IN_PROGRESS", "An operation can't be performed because a territory realignment is in progress." }, 
	{ "TEXT_DATA_OUTSIDE_SUPPORTED_CHARSET", "The specified text uses a character set that is not supported." }, 
	{ "TOO_MANY_APEX_REQUESTS", "Too many Apex requests have been sent. This error is transient. Resend your request after a short wait." }, 
	{ "TOO_MANY_ENUM_VALUE", "A request failed because too many values were passed in for a multi-select picklist. You can select a maximum of 100 values for a multi-select picklist." }, 
	{ "TRANSFER_REQUIRES_READ", "You can't assign the record to the specified User because the user does not have read permission." }, 
	{ "UNABLE_TO_LOCK_ROW", "A deadlock or timeout condition has been detected." }, 
	{ "UNAVAILABLE_RECORDTYPE_EXCEPTION", "The appropriate default record type could not be found." }, 
	{ "UNDELETE_FAILED", "An object could not be undeleted because it does not exist or has not been deleted." }, 
	{ "UNKNOWN_EXCEPTION", "The system encountered an internal error. Please report this problem to zuora.com." }, 
	{ "UNSPECIFIED_EMAIL_ADDRESS", "The specified user does not have an email address." }, 
	{ "UNSUPPORTED_APEX_TRIGGER_OPERATION", "You can't save recurring events with an Apex trigger." }, 
	{ "UNVERIFIED_SENDER_ADDRESS", "A sendEmail() call attempted to use an unverified email address defined in the OrgWideEmailAddress object." }, 
	{ "WEBLINK_SIZE_LIMIT_EXCEEDED", "The size of a WebLink URL or JavaScript code exceeds the limit." }, 
	{ "WEBLINK_URL_INVALID", "The WebLink URL has failed the URL string validation check." }, 
	{ "WRONG_CONTROLLER_TYPE", "The controller type for your Visualforce email template does not match the object type being used." }, 
	{ "Message send failed", "Unable to connect to zuora server." }, 
	{ "HOST_NOT_FOUND", "Unable to connect to zuora server." }, 
	{ "PASSWORD_EXPIRED", "Password provided in CSF key in order to connect to zuora.com has expired." }, 
	{ "MAX_SOBJECT_ERROR", "More than maximum allowed objects are selected. " }, 
	{ "MAX_SOBJECT_ERROR_TITLE", "Limit Exceeded" }, 
	{ "SUPPORTED_OPRATION_FILE_NOT_FOUND", "zuora supported file \"cloudAdapter-config-zuora_operationsSupported.xml\" is missing." }, 
	{ "SUPPORTED_API_FILE_NOT_FOUND", "zuora supported file \"cloudAdapter-config-zuora_APIsSupported.xml\" is missing." }, 
	{ "OPERATION_SUPPRESS_CB", "Suppress Response" }, 
	{ "OPERATION_SUPPRESS_TIP", "Suppresses zuora response for the selected operation" }, 
	{ "OPERATION_PROC_SUBMIT_REQ_CB", "ProcessSubmitRequest" }, 
	{ "OPERATION_PROC_SUBMIT_REQ_TIP", "Submit an array of objects to the approval process. Objects cannot already be in an approval process when submitted" }, 
	{ "OPERATION_PROC_WORK_ITEM_REQ_CB", "ProcessWorkitemRequest" }, 
	{ "OPERATION_PROC_WORK_ITEM_REQ_TIP", "Process an object that has been submitted to the approval process by performing an approval action (Approve or Reject)" }, 
	{ "OPERATION_PROCESS_CB_NOT_SELECTED_ERROR", "Please select either ProcessSubmitRequest or ProcessWorkitemRequest checkbox" }, 
	{ "OPERATION_PROCESS_CB_NOT_SELECTED_ERROR_TITLE", "Checkbox not selected" }, 
	{ "OP_QUERY_METADATA_ERROR", "Exception occurred while loading metadata for query statement parse.  Exception={0}" }, 
	{ "OP_METADATA_ERROR_TITLE", "Metadata Load Error" }, 
	{ "ADAPTER_COMPONENT_DESC", "A zuora Cloud adapter can send and receive messages from zuora Cloud server." }, 
	{ "ADAPTER_COMPONENT_NAME", "zuora" }, 
	{ "ADAPTER_COMPONENT_BINDING_SUBTYPE", "zuora" }, 
	{ "soapenv:Client", "No operation specified in request (the Body element has no child elements)" }, 
	{ "ST_EXECUTE_QUERY_LIMIT_EXCEED", "zuora may have more than 200 records." }, 
	{ "CACHE_DATA_NOT_AVAILABLE", "Metadata for the enterprise WSDL is not available in the cache." }, 
	{ "ADAPTER_COMPONENT_NAME_L", "zuora" }, 
	{ "SCA_ADAPTER_CLOUD_CATEGORY_NAME_L", "Cloud" }, 
	{ "CLOUD_ADAPTER_COMPONENT_FOLDER_NAME_L", "Cloud Adapters" }, 
	{ "HTTP_URL_NOT_SUPPORTED", "HTTP/HTTPS URLs are not supported by zuora Cloud Adapter" }, 
	{ "CL_CONNECTION_CREDENTIAL_UPDATE_TIP", "Update a authentication credential in CSF key store" }, 
	{ "CL_OP_UPDATE_WSDL_SCHEMA_WARNING", "The WSDL generated for this adapter is in use by other components. Removing business objects ({0} ) could break other components if they referencing the schema for the missing business objects. Do you want to continue?" }, 
	{ "CL_WIZARD_ARTIFACT_GENERATION_ERROR", "Exception occurred while generating artifacts.  Exception={0}" }, 
	{ "CL_WIZARD_ARTIFACT_GENERATION_ERROR_TITLE", "Artifact Generation Error" }, 
	{ "CL_OP_UPDATE_WSDL_WARNING_TITLE", "Updating Adapter WSDL Warning" }, 
	{ "CL_OP_UPDATE_WSDL_OPERATION_WARNING", "The WSDL generated for this adapter is in use by other components. Renaming the WSDL operation from {0} to {1} could break other components if they reference the old operation name. Do you want to continue?" }, 
	{ "CL_CONNECTION_EXCEPTION", "Connection to Sample Cloud Server failed. Exception = {0} ." }, 
	{ "CL_CREDENTIAL_CSFKEY_EXTRACT_ERROR", "The credential information for csfkey = {0} could not be found.  See log for possible exceptions." }, 
	{ "CL_WIZARD_CONFIG_FILE_PARSE_ERROR", "Parse of file {0} exception: {1}" }, 
	{ "CM_CN_CONNECTION_TEST_FAILURE_WITH_CAUSE", "Connection failure. reason = {0}  cause = {1}" }, 
	{ "CL_CREDENTIAL__ERROR_TITLE", "Credential Error" }, 
	{ "CM_CN_CONNECTION_TEST_FAILURE_SOAPFAULT", "Connection failure. reason = {0}  SOAPFault: = {1}" }, 
	{ "CM_CN_CONNECTION_TEST_FAILURE", "Connection failure. reason = {0}" }, 
	{ "CL_CREDENTIAL_CSFKEY_DUPLICATE_ERROR", "The csfkey = {0} already exists." }, 
	{ "CL_WIZARD_CONFIG_FILE_ERROR_TITLE", "Cloud Adapter Configuration File Error" }, 
	{ "CL_CREDENTIAL_CSFKEY_ADD_ERROR", "The credential for csfkey = {0} could not be added.  See log for possible exceptions." }, 
	{ "OP_OBJECT_NOT_QUERYABLE", "Error encountered parsing SOQL query statement. Object {0} is not queryable." }, 
	{ "OP_QUERY_RELATIONSHIP_NOT_FOUND", "Error encountered while getting data for {0} relationship" }, 
	{ "OP_INVALID_RELATIONSHIP_OBJECT_ERROR", "Error encountered parsing the statement. A relationship with the name {0} does not exists for {1} object." }, 
	{ "OP_ALIAS_NAME_NOT_ACC_TO_NCNAME", "Error encountered parsing the statement. Alias name \"{0}\" is not in accordance with XML NCName rules." }, 
	{ "INVALID_HEADER_ASSIGNMENTRULEID_VALUE_ERROR", "Invalid value for header : assignmentRuleId. It must start with \"01Q\"" }, 
	{ "OP_DUPLICATE_ALIAS", "Error encountered parsing the statement. Alias name \"{0}\" is used more than once." }, 
	{ "SELECTED_OPERATION_NAME", "Selected Operation Name: " }, 
	{ "SELECTED_SOBJECTS_NAME", "Selected Object(s) Name: " }, 
	{ "NO_HEADER_SELECTED", "No Header Selected" }, 
	{ "SELECTED_SOAP_HEADER", "Selected SOAP Header: " }, 
	{ "OP_ALIAS_NAME_NOT_ACC_TO_NCNAME", "Error encountered parsing the statement. Alias name \"{0}\" is not in accordance with XML NCName rules." }, 
	{ "INVALID_HEADER_ASSIGNMENTRULEID_VALUE_ERROR", "Invalid value for header : assignmentRuleId. It must start with \"01Q\"" }, 
	{ "OP_BLANK_BRACKET_ERROR", "Error encountered parsing the statement. Invalid function or only blank brackets found." }, 
	{ "OP_INVALID_AGR_FUNC_ERROR", "Error encountered parsing the statement. Invalid function found \"{0}\"" }, 
	{ "OP_FUNC_CLAUSE_MISSING", "Error encountered parsing the statement. Function clause missing" }, 
	{ "OP_INNER_QUERY_DATE_FUNC_ERR", "Error encountered parsing the statement. Inner queries does not support date functions" }, 
	{ "OP_QUERY_MISSING_TABLE", "Error encountered parsing the statement. No table specified to query." }, 
	{ "OP_QUERY_MISSING_COMMA", "Error encountered parsing the statement. Comma missing." }, 
	{ "OP_WSDL_OP_NAME_NOT_ACC_TO_NCNAME", "WSDL operation name is not in accordance with XML NCName rules." }, 
	{ "OP_QUERY_ALIAS_RESERVED", "Error encountered parsing the statement. Reserved keyword \"{0}\" can not be used as alias." } };
}
